# Uygulama ayarlar?
server:
  port: 8080

# Veritaban? ba?lant? ayarlar?
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ozlem
    username: postgres
    password: 1
  jpa:
    hibernate:
      ddl-auto: update #update  create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  database-platform: org.hibernate.dialect.PostgreSQLDialect






